M48
; DRILL file {KiCad 9.0.6} date 2026-03-02T22:48:27+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-02T22:48:27+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X100.923Y-83.36
X100.923Y-89.14
T2
X137.068Y-71.5
M30
